### PR TITLE
Support other exchange types and routing keys

### PR DESCRIPTION
**Pull request by danielfarrell**
This allows topic exchanges with routing keys not based off of names. It goes further than the other pull request with routing keys.

### CODE REVIEW

**Comment by jondot** [comment]
Hi Daniel, this pull looks great and I'd like to merge it. Looks like it's not based on the march_hare pull (or maybe not on all of it).
If you have any feedback before I'll merge the two manually - please let me know
I'll leave this pull request open for a bit for you to notice - thanks :+1:

**Comment by danielfarrell** [comment]
I'll update it to be based on the other one.  I did them separately so you'd have a pick of either/or.

**Comment by jondot** [comment]
Thanks - good thinking :)
I can also do the merge, no problems, LMK.

**Comment by danielfarrell** [comment]
This should be ready now.

**Comment by jondot** [comment]
awesome! merged! :+1:

**Pull request merged**
